# Generated by Django 2.2 on 2020-05-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EastAfrican',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ea_nin', models.CharField(max_length=20)),
                ('id_scan', models.ImageField(upload_to='')),
                ('medical_scan', models.ImageField(upload_to='')),
                ('payment_scan', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Foreigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('visa_no', models.CharField(max_length=20)),
                ('visa_scan', models.ImageField(upload_to='')),
                ('passport_no', models.CharField(max_length=20)),
                ('passport_scan', models.ImageField(upload_to='')),
                ('work_permit_no', models.CharField(blank=True, max_length=20, null=True)),
                ('wp_scan', models.ImageField(blank=True, null=True, upload_to='')),
                ('medical_scan', models.ImageField(upload_to='')),
                ('payment_scan', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ugandan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nin', models.CharField(max_length=20)),
                ('id_scan', models.ImageField(upload_to='')),
                ('medical_scan', models.ImageField(upload_to='')),
                ('payment_scan', models.ImageField(upload_to='')),
            ],
        ),
    ]
