# Generated by Django 2.2 on 2020-05-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(max_length=12)),
                ('scan', models.ImageField(upload_to='')),
                ('payment_scan', models.ImageField(upload_to='')),
            ],
        ),
    ]
